apiVersion: v1
kind: Service
metadata:
  name: {{ include "challenge.name" . }}
  labels:
    {{- include "challenge.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "challenge.labels.matchLabels" . | nindent 4 }}
  ports:
    {{- range $.Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      protocol: TCP
      name: {{ .name }}
      {{- if and .nodePort (eq $.Values.service.type "NodePort") }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
