{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "challenge.name" . }}-db
  labels:
    {{- include "challenge.labels.standard" . | nindent 4 }}
  namespace: {{ include "challenge.namespace" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "challenge.labels.matchLabels" . | nindent 4 }}
  ports:
    {{- range $.Values.database.containerPorts }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
{{- end }}
